lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem'
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:      '681b2a7cb32f6107509f95d35697f310df9414aaaf8386962411e2480d6eca21'
    token_ttl:        3600
