# config/packages/messenger.yaml

framework:
    messenger:
        # Die failure_transport-Konfiguration bleibt, falls andere
        # Nachrichten über den Messenger laufen.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # Der async-Transport kann bleiben, falls er für andere
            # Nachrichten verwendet wird.
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # WICHTIGE ÄNDERUNG: Die Klasse Symfony\Component\Mailer\Messenger\SendEmailMessage
            # wird NICHT mehr zum async-Transport geroutet.
            # Symfony wird die E-Mail jetzt direkt, also synchron, versenden.
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async

            # Chat- und SMS-Nachrichten werden weiterhin asynchron behandelt,
            # solange der Worker läuft.
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
