security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/login
            stateless: true
            
            json_login:
                check_path: /login
                username_path: email
                password_path: password
            custom_authenticator: App\Security\AppCustomAuthenticator

        api:
            pattern: ^/
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/posts, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/posts, roles: IS_AUTHENTICATED_FULLY , methods: [POST]}
        - { path: ^/api/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4      # Geringster Wert für bcrypt
                time_cost: 3 # Geringster Wert für argon
                memory_cost: 10 # Geringster Wert für argon
