# Expose your documentation as JSON swagger compliant
# JSON-Spezifikation (z. B. für Swagger Editor oder Postman)
app.swagger:
    path: /api/doc.json
    methods: [GET]
    defaults:
        _controller: nelmio_api_doc.controller.swagger

# Swagger UI im Browser
app.swagger_ui:
    path: /api/doc
    methods: [GET]
    defaults:
        _controller: nelmio_api_doc.controller.swagger_ui

